---
env:
  es6: true
  node: true
  jest: true
extends:
  - "airbnb-base"
  - "prettier"
rules:
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  quotes:
    - error
    - single
